# Enable lots of debugging output in the console (for troubleshooting)
debug: false

# Broadcast the location of each horse group spawned (debugging only!)
broadcast-location: false

# Worlds that horses should spawn in (one world per line)
horse-worlds:
  - world

# List of biomes that horses are allowed to spawn in (default: plains)
# Get the full list of valid names from: http://jd.bukkit.org/rb/apidocs/org/bukkit/block/Biome.html
horse-biomes:
  - plains
  
# MINIMUM time before more horses are able to spawn
spawn-delay: 180

# Only spawn horses if X surrounding chunks are animal free 
chunk-check-radius: 3

# Percent chance of spawning horse or donkey
spawn-chance: 1

# Percent chance that donkey will be spawned instead of a horse
donkey-chance: 10

# Min/max number of horses spawned in each group/herd
min-horses: 2
max-horses: 7